#!/bin/bash

echo "enter username mysql:"
read user
echo "enter password mysql:"
read password
db=erlang

mysql --user="$user" --password="$password" --database="$database" --execute='
										DROP DATABASE '$db'; 
										CREATE DATABASE '$db'; 
										USE '$db';' 



#	CREATE TABLE users (id VARCHAR(4), first_name VARCHAR(255), phone VARCHAR(4), age INT);
#	INSERT INTO users (id, first_name, phone, age) VALUES 
#								("1","Jonh","1115",25),
#								("2","Kevin","1785",18),
#								("3", "Nora", "4695", 36), 
#								("4", "David", "3964", 40), 
#								("5", "Fiona", "9358", 15), 
#								("6", "Andrew", "2574", 60), 
#								("7", "Lisa", "7563", 34), 
#								("8", "Stanly", "2745", 51), 
#								("9", "Sara", "4833", 12), 
#								("10", "Dash", "7866", 22);
#	SELECT * FROM users;'
	
	
#	DROP DATABASE '$database'; 
