FROM erlang:26

RUN git clone https://github.com/salvasser/Erlang
COPY factorial.erl factorial.erl

CMD chmod +x factorial.erl && echo "it is factorial calculator, please enter a number:" && read num && ./factorial.erl $num
